spring:
  profiles:
    active:
      - dev

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: dev
  application:
    name: micro-service-config-dev
---
spring:
  profiles: test
  application:
    name: micro-service-config-test
