spring:
  profiles:
    active:
    - dev
---
server:
  port: 7004
spring:
  profiles: dev
  application:
    name: micro-service-config-client-eureka
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7004.com:7004/eureka/
---
server:
  port: 7004
spring:
  profiles: test
  application:
    name: micro-service-config-client-eureka
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7004.com:7004/eureka/
